### ISSUE TITLE
一直不懂nodejs,vue,npm,前端,后端这些关系

### ISSUE THREAD

**Issue by TXIuTnVsbA** [MiYogurt/nodelover-maps#1]
我的理解是nodejs是用js语言的,然后npm是第三方扩展的管理，vue应该是第三方扩展吧？
然后就是搞不懂nodejs是前端还是后端,

**Comment by MiYogurt** [comment]
nodejs 一个运行环境，在这个环境下拥有交互操作系统的功能。
